# Generated by Django 5.0.6 on 2024-05-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trellis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(max_length=20),
        ),
    ]
